name: convert_db_format
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

  snout_db:
    path: ../snout_db

  cryptography: ^2.9.0
  webcrypto: any
  cbor: ^6.3.7

  snout_db_legacy:
    path: ../snout_db_legacy

dev_dependencies:
  lints: ^6.0.0
