name: server
publish_to: none
version: 1.2.0+3

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  eval_ex: ^1.1.8
  http: ^1.1.2
  logging: ^1.2.0
  rfc_6901: ^0.2.0

  shelf: ^1.4.2
  shelf_gzip: ^4.1.0
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0

  snout_db:
    path: ../snout_db

  synchronized: ^3.3.0+3
  web_socket_channel: ^3.0.2

dev_dependencies:
  lint: 2.3.0