name: snout_db
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  decimal: ^3.2.1
  eval_ex: ^1.2.0
  json_annotation: ^4.9.0

  meta: ^1.15.0
  rfc_6901: ^0.2.0
  

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  lint: ^2.3.0